version: '3'

services:
  web:
    env_file:
      - secrets.decrypted.env
    #image: kthregistryv2.sys.kth.se/search-web:${WEB_VERSION}
    build: .
    environment:
      WEB_VERSION: "^0.2.0"
      LDAP_TIMEOUT: 3000
      LDAP_CONNECT_TIMEOUT: 3000
      LDAP_MAX_IDLE_TIME: 300000
      SERVICE_PUBLISH : "/pipeline"
      NODE_ENV: "production"
      SERVER_HOST_URL: "https://app-r.referens.sys.kth.se"
      CAS_SSO_URI: "https://login-r.referens.sys.kth.se"
      CM_HOST_URL: "https://www.kth.se/cm/"
      SESSION_KEY: "flottsbro-web.sid"
      DISPLAY_APPS_IN_CLUSTER: "stage"
      
    ports:
      - 3000:3000
      
    tty: true

    labels:
      - se.kth.monitorUrl=https://app.kth.se/pipeline/_monitor
      - se.kth.cluster=stage
      - se.kth.slackChannels="#team-pipeline-build,#pipeline-logs"
      - se.kth.publicName.swedish="Flottsbro-web"
      - se.kth.publicName.english="Flottsbro-web"
      - se.kth.description.swedish="Visar information om applikationer som körs i våra kluster."
      - se.kth.description.english="Displays information about applications deployed in our clusters."