version: '3'

services:

  web:
    image: $LOCAL_IMAGE_ID
    environment: 
      - API_KEY
      
    tty: true
    
    ports:
      - 3000

  integration-tests:
    build: ./tests/integration-tests
    
