version: '3'

services:
  web:
    env_file:
      - .env
    
    build: .
    
    environment:
      LDAP_TIMEOUT: 3000
      LDAP_CONNECT_TIMEOUT: 3000
      LDAP_MAX_IDLE_TIME: 300000
      SERVICE_PUBLISH : "/pipeline"
      NODE_ENV: "production"
      SERVER_HOST_URL: "http://localhost:3000"
      CAS_SSO_URI: "https://login-r.referens.sys.kth.se"
      CM_HOST_URL: "https://www-r.referens.sys.kth.se/cm"
      SESSION_KEY: "flottsbro-web.sid"
      DISPLAY_APPS_IN_CLUSTER: "active"
      
    ports:
      - 3000:3000
      
    tty: true

    labels:
      - se.kth.monitorUrl=https://app.kth.se/pipeline/_monitor
      - se.kth.cluster=stage
      - se.kth.slackChannels="#team-pipeline-build,#pipeline-logs"
      - se.kth.publicName.swedish="Flottsbro-web"
      - se.kth.publicName.english="Flottsbro-web"
      - se.kth.description.swedish="Visar information om applikationer som körs i våra kluster."
      - se.kth.description.english="Displays information about applications deployed in our clusters."